# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.4.4
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_REMOTE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default


  liquibase:
    image: liquibase-mysql
    container_name: liquibase-test
    depends_on:
      mysql: 
        condition: service_healthy
    environment:
      INSTALL_MYSQL: true
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
    entrypoint: [
      "liquibase",
      "--defaultsFile=/liquibase/liquibase.properties",
      "update"
    ]
    networks:
      - default


volumes:
  mysql-data: