# docker-compose.yml

services:
  mysql:
    image: mysql:8.4.4
    container_name: mysql-test
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_REMOTE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  liquibase:
    image: liquibase-mysql
    container_name: liquibase-test
    depends_on:
      - mysql
    environment:
      INSTALL_MYSQL: true
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
    entrypoint: [
      "liquibase",
      "--defaultsFile=/liquibase/liquibase.properties",
      "update"
    ]


volumes:
  mysql-data: